CREATE DATABASE ERPHONIX
-- CREACION DE LA BASE DE DATOS
USE ERPHONIX
-- CREACION DE TABLAS
CREATE TABLE FACTURA (
FAC_UUID VARCHAR(36) PRIMARY KEY NOT NULL,
-- FAC_FACTURA BINARY, -- 0 = RECIBIDA, 1 = EMITIDA * (calculado)
FAC_VERSION VARCHAR(3),
FAC_TIPOCOMPROBANTE VARCHAR(1),
FAC_FECHAEMISION DATE,
FAC_FECHATIMBRADO DATETIME,
FAC_SERIE VARCHAR(25),
FAC_FOLIO VARCHAR(40),
FAC_RFCEMISOR VARCHAR(13),
FAC_NOMBREEMISOR VARCHAR(254),
FAC_REGIMENFISCAL VARCHAR(3),
FAC_LUGAREXPEDICION VARCHAR(5),
FAC_RFCRECEPTOR VARCHAR(13),
FAC_NOMBRERECEPTOR VARCHAR(254),
FAC_RESIDENCIAFISCAL VARCHAR(3), -- REVISAR EN CATALOGOS (COMO OBTENERLOS)
FAC_NUMREGIDTRIB VARCHAR(40),    -- LO MISMO X2
FAC_USOCFDI VARCHAR(3),
FAC_SUBTOTAL NUMERIC(10,2),
FAC_DESCUENTO NUMERIC(10,2),
FAC_TOTALIEPS NUMERIC (10,2),
FAC_IVA NUMERIC (10,2),
FAC_RETENIDOIVA NUMERIC(10,2),
FAC_RETENIDOISR NUMERIC(10,2),
FAC_TOTAL NUMERIC(10,2),
FAC_MONEDA VARCHAR(3),
FAC_TIPOCAMBIO NUMERIC(8,6),
FAC_FORMAPAGO VARCHAR(2),
FAC_METODOPAGO VARCHAR(3),
FAC_CONDICIONESPAGO VARCHAR(1000),
FAC_CONCEPTOS VARCHAR(1000),
)

CREATE TABLE NOMINA (
NOM_UUID VARCHAR(36), PRIMARY KEY NOT NULL,
NOM_FECHA DATE,
NOM_SERIE VARCHAR(25),
NOM_FOLIO VARCHAR(40),
NOM_RFCRECEPTOR VARCHAR(13),
NOM_NOMBRERECEPTOR VARCHAR(254),
NOM_RFCEMISOR VARCHAR(13),
NOM_NOMBREEMISOR VARCHAR(254),
NOM_REGISTROPATRONAL VARCHAR(20),
-- NOM_TIPONOMINA VARCHAR(15),*
NOM_FECHAPAGO DATE,
NOM_FECHAINICIALPAGO DATE,
NOM_FECHAFINALPAGO DATE,
NOM_NUMDIASPAGADOS NUMERIC(5,3),
NOM_SUBTOTAL NUMERIC(10,2),
NOM_DESCUENTO NUMERIC(10,2),
NOM_TOTAL NUMERIC(10,2),
NOM_METODOPAGO VARCHAR(3),
NOM_REGIMENFISCAL VARCHAR(3),
NOM_CONCEPTOS VARCHAR(1000),
NOM_TIPOCOMPROBANTE VARCHAR(1),
NOM_VERSION VARCHAR(3),
NOM_MONEDA VARCHAR(3),
NOM_TIPOCAMBIO NUMERIC(8,6),
NOM_RECEPTORCURP VARCHAR(18),
NOM_NUMSEGSOCIAL VARCHAR(15),
NOM_FECHAINIRELLAB DATE,
NOM_ANTIGUEDAD VARCHAR(10),
NOM_TIPOCONTRATO VARCHAR(2),
NOM_SINDICALIZADO VARCHAR(2),
NOM_TIPOJORNADA VARCHAR(2),
NOM_TIPOREGIMEN VARCHAR(2),
NOM_NUMEMPLEADO VARCHAR(15),
NOM_DEPARTAMENTO VARCHAR(100),
NOM_PUESTO VARCHAR(100),
NOM_RIESGOPUESTO VARCHAR(2),
NOM_PERIOINIPAGO VARCHAR(2),
NOM_BANCO VARCHAR(3),
NOM_CTABANCARIA INT(18),
NOM_SALDOBACOAP NUMERIC(20,2),
NOM_SALARIODI NUMERIC(20,2),
NOM_CVEENTFED VARCHAR(3),
NOM_TOTALSUELDOSPER NUMERIC(10,2),
NOM_TOTALSEPINDPER NUMERIC(10,2),
NOM_TOTALJUBPENSRET NUMERIC(10,2),
NOM_TOTALEXENTOPER NUMERIC(10,2),
NOM_TOTALOTRASDED NUMERIC(10,2),
NOM_TOTALIMPRETEN NUMERIC(10,2),
-- NOM_P01_SUE_SA_EX NUMERIC(10,2),*
-- NOM_P01_SUE_SA_GR NUMERIC(10,2),*
-- NOM_P02_AGUIN_EX NUMERIC(10,2),*
-- NOM_P02_AGUIN_GR NUMERIC(10,2),*
-- NOM_P03_UTIL_EX NUMERIC(10,2),*
-- NOM_P03_UTIL_GR NUMERIC(10,2),*
-- NOM_P06_CAJDH_EX NUMERIC(10,2),*
-- NOM_P06_CAJDH_GR NUMERIC(10,2),*
-- NOM_P09_CONT_EX NUMERIC(10,2),*
-- NOM_P10_PRPUN_EX NUMERIC(10,2),*
-- NOM_P10_PRPUN_GR NUMERIC(10,2),*
-- NOM_P14_INCAP_EX NUMERIC(10,2),*
-- NOM_P14_INCAP_GR NUMERIC(10,2),*
-- NOM_P19_HOREXT_EX NUMERIC(10,2),*
-- NOM_P19_HOREXT_GR NUMERIC(10,2),*
-- NOM_P20_PRIDOM_EX NUMERIC(10,2),*
-- NOM_P20_PRIDOM_GR NUMERIC(10,2),*
-- NOM_P21_PRIVAC_EX NUMERIC(10,2),*
-- NOM_P21_PRIVAC_GR NUMERIC(10,2),*
-- NOM_P25_INDEMN_EX NUMERIC(10,2),*
-- NOM_P25_INDEMN_GR NUMERIC(10,2),*
-- NOM_P38_OTRING_EX NUMERIC(10,2),*
-- NOM_P38_OTRING_GR NUMERIC(10,2),*
-- NOM_P49_PRASIST_EX NUMERIC(10,2),*
-- NOM_P49_PRASIST_GR NUMERIC(10,2),*
-- NOM_D01_SEGSOC NUMERIC(10,2),*
-- NOM_D02_ISR NUMERIC(10,2),*
-- NOM_D05_FONVIV NUMERIC(10,2),*
-- NOM_D09_INFONAVIT NUMERIC(10,2),*
-- NOM_D10_CRVIV NUMERIC(10,2),*
-- NOM_D12_ANTSAL NUMERIC(10,2),*
-- NOM_D21_CUOBPA NUMERIC(10,2),*
-- NOM_D71_SUBSEE NUMERIC(10,2),*
-- NOM_OP002_SUBSEM NUMERIC(10,2),*
)

CREATE TABLE EMPRESA (
EMP_RFC VARCHAR(13) NOT NULL PRIMARY KEY,
EMP_NOMBRE VARCHAR(254),
EMP_CORREO VARCHAR(120),
EMP_CVESAT VARCHAR(8)
-- EMP_DIRECCION VARCHAR(254)* 
)

CREATE TABLE BANCOS (
)

-- AVANCE HASTA 2018-08-09--