USE ERPHONIX;

-- --------------------------------------- PROCEDIMIENTOS PARA TABLA FACTURA -----------------------------

CREATE PROCEDURE AGREGAFACTURA (
	@UUID AS NVARCHAR(36),
    @FAC_FACTURA AS BINARY, -- 0 = RECIBIDA, 1 = EMITIDA * (calculado)
	@FAC_VERSION AS VARCHAR(3),
	@FAC_SERIE AS VARCHAR(25),
	@FAC_FOLIO AS VARCHAR(40),
	@FAC_FECHAEMISION AS DATE,
	@FAC_FORMAPAGO AS VARCHAR(2),
	@FAC_CONDICIONESPAGO AS VARCHAR(1000),
	@FAC_SUBTOTAL AS NUMERIC(10,2),
	@FAC_DESCUENTO AS NUMERIC(10,2),
	@FAC_MONEDA AS VARCHAR(3),
	@FAC_TIPOCAMBIO AS NUMERIC(8,6),
	@FAC_TOTAL AS NUMERIC(10,2),
	@FAC_TIPOCOMPROBANTE AS VARCHAR(1),
	@FAC_METODOPAGO AS VARCHAR(3),
	@FAC_LUGAREXPEDICION AS VARCHAR(5),
	@FAC_RFCEMISOR AS VARCHAR(13),
	@FAC_NOMBREEMISOR AS VARCHAR(254),
	@FAC_REGIMENFISCAL AS VARCHAR(3),
	@FAC_RFCRECEPTOR AS VARCHAR(13),
	@FAC_NOMBRERECEPTOR AS VARCHAR(254),
	@FAC_RESIDENCIAFISCAL AS VARCHAR(3),
	@FAC_NUMREGIDTRIB AS VARCHAR(40),
	@FAC_USOCFDI AS VARCHAR(3),
	@FAC_CONCEPTOS AS VARCHAR(1000),
	@FAC_RETENIDOIVA AS NUMERIC(10,2),
	@FAC_RETENIDOISR AS NUMERIC(10,2),
	@FAC_IVA AS NUMERIC (10,2),
	@FAC_TOTALIEPS AS NUMERIC (10,2),
	@FAC_FECHATIMBRADO AS DATETIME,
	@NOM_REGISTROPATRONAL AS VARCHAR(20),
	@NOM_TIPONOMINA AS VARCHAR(1),
	@NOM_FECHAPAGO AS DATE,
	@NOM_FECHAINICIALPAGO AS DATE,
	@NOM_FECHAFINALPAGO AS DATE,
	@NOM_NUMDIASPAGADOS AS NUMERIC(5,3),
	@NOM_REGIMENFISCAL AS VARCHAR(3),
	@NOM_RECEPTORCURP AS VARCHAR(18),
	@NOM_NUMSEGSOCIAL AS VARCHAR(15),
	@NOM_FECHAINIRELLAB AS DATE,
	@NOM_ANTIGUEDAD AS VARCHAR(10),
	@NOM_TIPOCONTRATO AS VARCHAR(2),
	@NOM_SINDICALIZADO AS VARCHAR(2),
	@NOM_TIPOJORNADA AS VARCHAR(2),
	@NOM_TIPOREGIMEN AS VARCHAR(2),
	@NOM_NUMEMPLEADO AS VARCHAR(15),
	@NOM_DEPARTAMENTO AS VARCHAR(100),
	@NOM_PUESTO AS VARCHAR(100),
	@NOM_RIESGOPUESTO AS VARCHAR(2),
	@NOM_PERIOINIPAGO AS VARCHAR(2),
	@NOM_BANCO AS VARCHAR(3),
	@NOM_CTABANCARIA AS INT(18),
	@NOM_SALDOBACOAP AS NUMERIC(20,2),
	@NOM_SALARIODI AS NUMERIC(20,2),
	@NOM_CVEENTFED AS VARCHAR(3),
	@NOM_TOTALSUELDOSPER AS NUMERIC(10,2),
	@NOM_TOTALSEPINDPER AS NUMERIC(10,2),
	@NOM_TOTALJUBPENSRET AS NUMERIC(10,2),
	@NOM_TOTALEXENTOPER AS NUMERIC(10,2),
	@NOM_TOTALOTRASDED AS NUMERIC(10,2),
	@NOM_TOTALIMPRETEN AS NUMERIC(10,2),
	@NOM_P01_SUE_SA_EX AS NUMERIC(20,2),
	@NOM_P01_SUE_SA_GR AS NUMERIC(20,2),
	@NOM_P02_AGUIN_EX AS NUMERIC(20,2),
	@NOM_P02_AGUIN_GR AS NUMERIC(20,2),
	@NOM_P03_UTIL_EX AS NUMERIC(20,2),
	@NOM_P03_UTIL_GR AS NUMERIC(20,2),
	@NOM_P04_GASMED_EX AS NUMERIC(20,2),
	@NOM_P04_GASMED_GR AS NUMERIC(20,2),
	@NOM_P05_FONAHO_EX AS NUMERIC(20,2),
	@NOM_P05_FONAHO_EX AS NUMERIC(20,2),
	@NOM_P06_CAJDH_EX AS NUMERIC(20,2),
	@NOM_P06_CAJDH_GR AS NUMERIC(20,2),
	@NOM_P09_CONT_EX AS NUMERIC(20,2),
	@NOM_P10_PRPUN_EX AS NUMERIC(20,2),
	@NOM_P10_PRPUN_GR AS NUMERIC(20,2),
	@NOM_P11_PRISEG_EX AS NUMERIC(20,2),
	@NOM_P11_PRISEG_GR AS NUMERIC(20,2),
	@NOM_P12_GASMED_EX AS NUMERIC(20,2),
	@NOM_P12_GASMED_GR AS NUMERIC(20,2),
	@NOM_P13_CUOSIN_EX AS NUMERIC(20,2),
	@NOM_P13_CUOSIN_GR AS NUMERIC(20,2),
	@NOM_P14_INCAP_EX AS NUMERIC(20,2),
	@NOM_P14_INCAP_GR AS NUMERIC(20,2),
	@NOM_P15_BECAS_EX AS NUMERIC(20,2),
	@NOM_P15_BECAS_GR AS NUMERIC(20,2),
	@NOM_P19_HRSEXT_EX AS NUMERIC(20,2),
	@NOM_P19_HRSEXT_GR AS NUMERIC(20,2),
	@NOM_P20_PRMDOM_EX AS NUMERIC(20,2),
	@NOM_P20_PRMDOM_GR AS NUMERIC(20,2),
	@NOM_P21_PRMVAC_EX AS NUMERIC(20,2),
	@NOM_P21_PRMVAC_GR AS NUMERIC(20,2),
	@NOM_P22_PRMANT_EX AS NUMERIC(20,2),
	@NOM_P22_PRMANT_GR AS NUMERIC(20,2),
	@NOM_P23_PSEPAR_EX AS NUMERIC(20,2),
	@NOM_P23_PSEPAR_GR AS NUMERIC(20,2),
	@NOM_P24_SGRETI_EX AS NUMERIC(20,2),
	@NOM_P24_SGRETI_GR AS NUMERIC(20,2),
	@NOM_P25_INDEMN_EX AS NUMERIC(20,2),
	@NOM_P25_INDEMN_GR AS NUMERIC(20,2),
	@NOM_P26_RFUNER_EX AS NUMERIC(20,2),
	@NOM_P26_RFUNER_GR AS NUMERIC(20,2),
	@NOM_P27_CUOSEG_EX AS NUMERIC(20,2),
	@NOM_P27_CUOSEG_GR AS NUMERIC(20,2),
	@NOM_P28_COMIS_EX AS NUMERIC(20,2),
	@NOM_P28_COMIS_GR AS NUMERIC(20,2),
	@NOM_P29_VALDSP_EX AS NUMERIC(20,2),
	@NOM_P29_VALDSP_GR AS NUMERIC(20,2),
	@NOM_P30_VALRES_EX AS NUMERIC(20,2),
	@NOM_P30_VALRES_GR AS NUMERIC(20,2),
	@NOM_P31_VALGAS_EX AS NUMERIC(20,2),
	@NOM_P31_VALGAS_GR AS NUMERIC(20,2),
	@NOM_P32_VALROP_EX AS NUMERIC(20,2),
	@NOM_P32_VALROP_GR AS NUMERIC(20,2),
	@NOM_P33_AYRENT_EX AS NUMERIC(20,2),
	@NOM_P33_AYRENT_GR AS NUMERIC(20,2),
	@NOM_P34_ARTESC_EX AS NUMERIC(20,2),
	@NOM_P34_ARTESC_GR AS NUMERIC(20,2),
	@NOM_P35_AYLENT_EX AS NUMERIC(20,2),
	@NOM_P35_AYLENT_GR AS NUMERIC(20,2),
	@NOM_P36_TRANSP_EX AS NUMERIC(20,2),
	@NOM_P36_TRANSP_GR AS NUMERIC(20,2),
	@NOM_P37_GFUNER_EX AS NUMERIC(20,2),
	@NOM_P37_GFUNER_GR AS NUMERIC(20,2),
	@NOM_P38_OTRING_EX AS NUMERIC(20,2),
	@NOM_P38_OTRING_GR AS NUMERIC(20,2),
	@NOM_P39_JUBILA_EX AS NUMERIC(20,2),
	@NOM_P39_JUBILA_GR AS NUMERIC(20,2),
	@NOM_P44_JUBPAR_EX AS NUMERIC(20,2),
	@NOM_P44_JUBPAR_GR AS NUMERIC(20,2),
	@NOM_P45_BIENES_EX AS NUMERIC(20,2),
	@NOM_P45_BIENES_GR AS NUMERIC(20,2),
	@NOM_P46_ASIMIL_EX AS NUMERIC(20,2),
	@NOM_P46_ASIMIL_GR AS NUMERIC(20,2),
	@NOM_P47_ALIMEN_EX AS NUMERIC(20,2),
	@NOM_P47_ALIMEN_GR AS NUMERIC(20,2),
	@NOM_P48_HABIT_EX AS NUMERIC(20,2),
	@NOM_P48_HABIT_GR AS NUMERIC(20,2),
	@NOM_P49_ASIST_EX AS NUMERIC(20,2),
	@NOM_P49_ASIST_GR AS NUMERIC(20,2),
	@NOM_P50_VIATIC_EX AS NUMERIC(20,2),
	@NOM_P50_VIATIC_GR AS NUMERIC(20,2),
	@NOM_D001_SEGSOC AS NUMERIC(20,2),
	@NOM_D002_ISR AS NUMERIC(20,2),
	@NOM_D003_APRETI AS NUMERIC(20,2),
	@NOM_D004_OTROS AS NUMERIC(20,2),
	@NOM_D005_FONVIV AS NUMERIC(20,2),
	@NOM_D006_DESINC AS NUMERIC(20,2),
	@NOM_D007_PNALIM AS NUMERIC(20,2),
	@NOM_D008_RENTA AS NUMERIC(20,2),
	@NOM_D009_INFONAVIT AS NUMERIC(20,2),
	@NOM_D010_CRVIV AS NUMERIC(20,2),
	@NOM_D011_INFONACOT AS NUMERIC(20,2),
	@NOM_D012_ANTSAL AS NUMERIC(20,2),
	@NOM_D013_EXCESO AS NUMERIC(20,2),
	@NOM_D014_ERRORES AS NUMERIC(20,2),
	@NOM_D015_PERDIDA AS NUMERIC(20,2),
	@NOM_D016_AVERIAS AS NUMERIC(20,2),
	@NOM_D017_AAPPEE AS NUMERIC(20,2),
	@NOM_D018_CCFSCCA AS NUMERIC(20,2),
	@NOM_D019_CUOSIND AS NUMERIC(20,2),
	@NOM_D020_AUSENC AS NUMERIC(20,2),
	@NOM_D021_CUOBPA AS NUMERIC(20,2),
	@NOM_D022_IMPLOC AS NUMERIC(20,2),
	@NOM_D023_APOVOL AS NUMERIC(20,2),
	@NOM_D024_AGUINEX AS NUMERIC(20,2),
	@NOM_D025_AGUINGR AS NUMERIC(20,2),
	@NOM_D026_APTUEX AS NUMERIC(20,2),
	@NOM_D027_APTUGR AS NUMERIC(20,2),
	@NOM_D028_GASMEDEX AS NUMERIC(20,2),
	@NOM_D029_FONAHOEX AS NUMERIC(20,2),
	@NOM_D030_CAJAHOEX AS NUMERIC(20,2),
	@NOM_D031_ACCTPPEX AS NUMERIC(20,2),
	@NOM_D032_PUNTGR AS NUMERIC(20,2),
	@NOM_D033_SEGVIDEX AS NUMERIC(20,2),
	@NOM_D034_GASMEDEX AS NUMERIC(20,2),
	@NOM_D035_COUSINEX AS NUMERIC(20,2),
	@NOM_D036_SUBINCEX AS NUMERIC(20,2),
	@NOM_D037_BECTREX AS NUMERIC(20,2),
	@NOM_D038_AHREXTEX AS NUMERIC(20,2),
	@NOM_D039_AHREXTGR AS NUMERIC(20,2),
	@NOM_D040_APRDOMEX AS NUMERIC(20,2),
	@NOM_D041_APRDOMGR AS NUMERIC(20,2),
	@NOM_D042_APRVACEX AS NUMERIC(20,2),
	@NOM_D043_APRVACGR AS NUMERIC(20,2),
	@NOM_D044_APRANTEX AS NUMERIC(20,2),
	@NOM_D045_APRANTGR AS NUMERIC(20,2),
	@NOM_D046_APGSEPEX AS NUMERIC(20,2),
	@NOM_D047_APGSEPGR AS NUMERIC(20,2),
	@NOM_D048_ASGRETEX AS NUMERIC(20,2),
	@NOM_D049_AINDEMEX AS NUMERIC(20,2),
	@NOM_D050_AINDEMGR AS NUMERIC(20,2),
	@NOM_D051_AREFUNEX AS NUMERIC(20,2),
	@NOM_D052_ACSPPPEX AS NUMERIC(20,2),
	@NOM_D053_ACOMIGR AS NUMERIC(20,2),
	@NOM_D054_AVADESEX AS NUMERIC(20,2),
	@NOM_D055_AVARESEX AS NUMERIC(20,2),
	@NOM_D056_AVAGASEX AS NUMERIC(20,2),
	@NOM_D057_AVAROPEX AS NUMERIC(20,2),
	@NOM_D058_AAYRENEX AS NUMERIC(20,2),
	@NOM_D059_AAYASCEX AS NUMERIC(20,2),
	@NOM_D060_AAYANTEX AS NUMERIC(20,2),
	@NOM_D061_AAYTEXEX AS NUMERIC(20,2),
	@NOM_D062_AAYGFUEX AS NUMERIC(20,2),
	@NOM_D063_AOINSAEX AS NUMERIC(20,2),
	@NOM_D064_AOINSAGR AS NUMERIC(20,2),
	@NOM_D065_AJUBILEX AS NUMERIC(20,2),
	@NOM_D066_AJUBILGR AS NUMERIC(20,2),
	@NOM_D067_APGSA AS NUMERIC(20,2),
	@NOM_D068_APGSNA AS NUMERIC(20,2),
	@NOM_D069_AJUBA AS  NUMERIC(20,2),
	@NOM_D070_AJUBNA AS NUMERIC(20,2),
	@NOM_D071_SUBSEE AS NUMERIC(20,2),
	@NOM_D072_ABIENEX AS NUMERIC(20,2),
	@NOM_D073_ABIENGR AS NUMERIC(20,2),
	@NOM_D074_AALIMEX AS NUMERIC(20,2),
	@NOM_D075_AALIMGR AS NUMERIC(20,2),
	@NOM_D076_AHABIEX AS NUMERIC(20,2),
	@NOM_D077_AHABIGR AS NUMERIC(20,2),
	@NOM_D078_APRASIS AS NUMERIC(20,2),
	@NOM_D079_AJOTPAG AS NUMERIC(20,2),
	@NOM_D080_AVIATGR AS NUMERIC(20,2),
	@NOM_D081_AVIATET AS NUMERIC(20,2),
	@NOM_D082_AFOAHGR AS NUMERIC(20,2),
	@NOM_D083_ACAAHGR AS NUMERIC(20,2),
	@NOM_D084_APRSVGR AS NUMERIC(20,2),
	@NOM_D085_ASGMMGR AS NUMERIC(20,2),
	@NOM_D086_AINCAGR AS NUMERIC(20,2),
	@NOM_D087_ABECAGR AS NUMERIC(20,2),
	@NOM_D088_ASRETGR AS NUMERIC(20,2),
	@NOM_D089_AVADEGR AS NUMERIC(20,2),
	@NOM_D090_AVAREGR AS NUMERIC(20,2),
	@NOM_D091_AVAGAGR AS NUMERIC(20,2),
	@NOM_D092_AVAROGR AS NUMERIC(20,2),
	@NOM_D093_AAYREGR AS NUMERIC(20,2),
	@NOM_D094_AAYAEGR AS NUMERIC(20,2),
	@NOM_D095_AAYANGR AS NUMERIC(20,2),
	@NOM_D096_AAYTRGR AS NUMERIC(20,2),
	@NOM_D097_AAYFUGR AS NUMERIC(20,2),
	@NOM_D098_AINASGR AS NUMERIC(20,2),
	@NOM_D099_AINSSGR AS NUMERIC(20,2),
	@NOM_D100_AVIEXGR AS NUMERIC(20,2),
	@NOM_D101_ISRREEA AS NUMERIC(20,2),
	@NOM_OP002_SUBSEM AS NUMERIC(20,2)
    )
    AS
		IF EXISTS (SELECT FAC_UUID FORM FACTURA WHERE FAC_UUID = @FAC_UUID)
        BEGIN
			SELECT '0'		-- NO SE AGREGARÁ, PUES YA EXISTE UNA FACTURA CON ESE UUID
		END
        ELSE
        BEGIN
			INSERT INTO FACTURA VALUES
			(@UUID,
			@FAC_FACTURA, -- 0 = RECIBIDA, 1 = EMITIDA * (calculado)
			@FAC_VERSION,
			@FAC_SERIE,
			@FAC_FOLIO,
			@FAC_FECHAEMISION,
			@FAC_FORMAPAGO,
			@FAC_CONDICIONESPAGO,
			@FAC_SUBTOTAL,
			@FAC_DESCUENTO,
			@FAC_MONEDA,
			@FAC_TIPOCAMBIO,
			@FAC_TOTAL,
			@FAC_TIPOCOMPROBANTE,
			@FAC_METODOPAGO,
			@FAC_LUGAREXPEDICION,
			@FAC_RFCEMISOR,
			@FAC_NOMBREEMISOR,
			@FAC_REGIMENFISCAL,
			@FAC_RFCRECEPTOR,
			@FAC_NOMBRERECEPTOR,
			@FAC_RESIDENCIAFISCAL,
			@FAC_NUMREGIDTRIB,
			@FAC_USOCFDI,
			@FAC_CONCEPTOS,
			@FAC_RETENIDOIVA,
			@FAC_RETENIDOISR,
			@FAC_IVA,
			@FAC_TOTALIEPS,
			@FAC_FECHATIMBRADO,
			@NOM_REGISTROPATRONAL,
			@NOM_TIPONOMINA,
			@NOM_FECHAPAGO,
			@NOM_FECHAINICIALPAGO,
			@NOM_FECHAFINALPAGO,
			@NOM_NUMDIASPAGADOS,
			@NOM_REGIMENFISCAL,
			@NOM_RECEPTORCURP,
			@NOM_NUMSEGSOCIAL,
			@NOM_FECHAINIRELLAB,
			@NOM_ANTIGUEDAD,
			@NOM_TIPOCONTRATO,
			@NOM_SINDICALIZADO,
			@NOM_TIPOJORNADA,
			@NOM_TIPOREGIMEN,
			@NOM_NUMEMPLEADO,
			@NOM_DEPARTAMENTO,
			@NOM_PUESTO,
			@NOM_RIESGOPUESTO,
			@NOM_PERIOINIPAGO,
			@NOM_BANCO,
			@NOM_CTABANCARIA,
			@NOM_SALDOBACOAP,
			@NOM_SALARIODI,
			@NOM_CVEENTFED,
			@NOM_TOTALSUELDOSPER,
			@NOM_TOTALSEPINDPER,
			@NOM_TOTALJUBPENSRET,
			@NOM_TOTALEXENTOPER,
			@NOM_TOTALOTRASDED,
			@NOM_TOTALIMPRETEN,
			@NOM_P01_SUE_SA_EX,
			@NOM_P01_SUE_SA_GR,
			@NOM_P02_AGUIN_EX,
			@NOM_P02_AGUIN_GR,
			@NOM_P03_UTIL_EX,
			@NOM_P03_UTIL_GR,
			@NOM_P04_GASMED_EX,
			@NOM_P04_GASMED_GR,
			@NOM_P05_FONAHO_EX,
			@NOM_P05_FONAHO_EX,
			@NOM_P06_CAJDH_EX,
			@NOM_P06_CAJDH_GR,
			@NOM_P09_CONT_EX,
			@NOM_P10_PRPUN_EX,
			@NOM_P10_PRPUN_GR,
			@NOM_P11_PRISEG_EX,
			@NOM_P11_PRISEG_GR,
			@NOM_P12_GASMED_EX,
			@NOM_P12_GASMED_GR,
			@NOM_P13_CUOSIN_EX,
			@NOM_P13_CUOSIN_GR,
			@NOM_P14_INCAP_EX,
			@NOM_P14_INCAP_GR,
			@NOM_P15_BECAS_EX,
			@NOM_P15_BECAS_GR,
			@NOM_P19_HRSEXT_EX,
			@NOM_P19_HRSEXT_GR,
			@NOM_P20_PRMDOM_EX,
			@NOM_P20_PRMDOM_GR,
			@NOM_P21_PRMVAC_EX,
			@NOM_P21_PRMVAC_GR,
			@NOM_P22_PRMANT_EX,
			@NOM_P22_PRMANT_GR,
			@NOM_P23_PSEPAR_EX,
			@NOM_P23_PSEPAR_GR,
			@NOM_P24_SGRETI_EX,
			@NOM_P24_SGRETI_GR,
			@NOM_P25_INDEMN_EX,
			@NOM_P25_INDEMN_GR,
			@NOM_P26_RFUNER_EX,
			@NOM_P26_RFUNER_GR,
			@NOM_P27_CUOSEG_EX,
			@NOM_P27_CUOSEG_GR,
			@NOM_P28_COMIS_EX,
			@NOM_P28_COMIS_GR,
			@NOM_P29_VALDSP_EX,
			@NOM_P29_VALDSP_GR,
			@NOM_P30_VALRES_EX,
			@NOM_P30_VALRES_GR,
			@NOM_P31_VALGAS_EX,
			@NOM_P31_VALGAS_GR,
			@NOM_P32_VALROP_EX,
			@NOM_P32_VALROP_GR,
			@NOM_P33_AYRENT_EX,
			@NOM_P33_AYRENT_GR,
			@NOM_P34_ARTESC_EX,
			@NOM_P34_ARTESC_GR,
			@NOM_P35_AYLENT_EX,
			@NOM_P35_AYLENT_GR,
			@NOM_P36_TRANSP_EX,
			@NOM_P36_TRANSP_GR,
			@NOM_P37_GFUNER_EX,
			@NOM_P37_GFUNER_GR,
			@NOM_P38_OTRING_EX,
			@NOM_P38_OTRING_GR,
			@NOM_P39_JUBILA_EX,
			@NOM_P39_JUBILA_GR,
			@NOM_P44_JUBPAR_EX,
			@NOM_P44_JUBPAR_GR,
			@NOM_P45_BIENES_EX,
			@NOM_P45_BIENES_GR,
			@NOM_P46_ASIMIL_EX,
			@NOM_P46_ASIMIL_GR,
			@NOM_P47_ALIMEN_EX,
			@NOM_P47_ALIMEN_GR,
			@NOM_P48_HABIT_EX,
			@NOM_P48_HABIT_GR,
			@NOM_P49_ASIST_EX,
			@NOM_P49_ASIST_GR,
			@NOM_P50_VIATIC_EX,
			@NOM_P50_VIATIC_GR,
			@NOM_D001_SEGSOC,
			@NOM_D002_ISR,
			@NOM_D003_APRETI,
			@NOM_D004_OTROS,
			@NOM_D005_FONVIV,
			@NOM_D006_DESINC,
			@NOM_D007_PNALIM,
			@NOM_D008_RENTA,
			@NOM_D009_INFONAVIT,
			@NOM_D010_CRVIV,
			@NOM_D011_INFONACOT,
			@NOM_D012_ANTSAL,
			@NOM_D013_EXCESO,
			@NOM_D014_ERRORES,
			@NOM_D015_PERDIDA,
			@NOM_D016_AVERIAS,
			@NOM_D017_AAPPEE,
			@NOM_D018_CCFSCCA,
			@NOM_D019_CUOSIND,
			@NOM_D020_AUSENC,
			@NOM_D021_CUOBPA,
			@NOM_D022_IMPLOC,
			@NOM_D023_APOVOL,
			@NOM_D024_AGUINEX,
			@NOM_D025_AGUINGR,
			@NOM_D026_APTUEX,
			@NOM_D027_APTUGR,
			@NOM_D028_GASMEDEX,
			@NOM_D029_FONAHOEX,
			@NOM_D030_CAJAHOEX,
			@NOM_D031_ACCTPPEX,
			@NOM_D032_PUNTGR,
			@NOM_D033_SEGVIDEX,
			@NOM_D034_GASMEDEX,
			@NOM_D035_COUSINEX,
			@NOM_D036_SUBINCEX,
			@NOM_D037_BECTREX,
			@NOM_D038_AHREXTEX,
			@NOM_D039_AHREXTGR,
			@NOM_D040_APRDOMEX,
			@NOM_D041_APRDOMGR,
			@NOM_D042_APRVACEX,
			@NOM_D043_APRVACGR,
			@NOM_D044_APRANTEX,
			@NOM_D045_APRANTGR,
			@NOM_D046_APGSEPEX,
			@NOM_D047_APGSEPGR,
			@NOM_D048_ASGRETEX,
			@NOM_D049_AINDEMEX,
			@NOM_D050_AINDEMGR,
			@NOM_D051_AREFUNEX,
			@NOM_D052_ACSPPPEX,
			@NOM_D053_ACOMIGR,
			@NOM_D054_AVADESEX,
			@NOM_D055_AVARESEX,
			@NOM_D056_AVAGASEX,
			@NOM_D057_AVAROPEX,
			@NOM_D058_AAYRENEX,
			@NOM_D059_AAYASCEX,
			@NOM_D060_AAYANTEX,
			@NOM_D061_AAYTEXEX,
			@NOM_D062_AAYGFUEX,
			@NOM_D063_AOINSAEX,
			@NOM_D064_AOINSAGR,
			@NOM_D065_AJUBILEX,
			@NOM_D066_AJUBILGR,
			@NOM_D067_APGSA,
			@NOM_D068_APGSNA,
			@NOM_D069_AJUBA,
			@NOM_D070_AJUBNA,
			@NOM_D071_SUBSEE,
			@NOM_D072_ABIENEX,
			@NOM_D073_ABIENGR,
			@NOM_D074_AALIMEX,
			@NOM_D075_AALIMGR,
			@NOM_D076_AHABIEX,
			@NOM_D077_AHABIGR,
			@NOM_D078_APRASIS,
			@NOM_D079_AJOTPAG,
			@NOM_D080_AVIATGR,
			@NOM_D081_AVIATET,
			@NOM_D082_AFOAHGR,
			@NOM_D083_ACAAHGR,
			@NOM_D084_APRSVGR,
			@NOM_D085_ASGMMGR,
			@NOM_D086_AINCAGR,
			@NOM_D087_ABECAGR,
			@NOM_D088_ASRETGR,
			@NOM_D089_AVADEGR,
			@NOM_D090_AVAREGR,
			@NOM_D091_AVAGAGR,
			@NOM_D092_AVAROGR,
			@NOM_D093_AAYREGR,
			@NOM_D094_AAYAEGR,
			@NOM_D095_AAYANGR,
			@NOM_D096_AAYTRGR,
			@NOM_D097_AAYFUGR,
			@NOM_D098_AINASGR,
			@NOM_D099_AINSSGR,
			@NOM_D100_AVIEXGR,
			@NOM_D101_ISRREEA,
			@NOM_OP002_SUBSEM
			)
			SELECT '1'
			END
            
CREATE PROCEDURE ELIMINAFACTURA (@UUID AS NVARCHAR)
AS
	IF EXISTS (SELECT * FROM FACTURA WHERE FAC_UUID = @UUID)
	BEGIN
		DELETE FROM FACTURA WHERE FAC_UUID = @UUID
        SELECT'1'
	END
	ELSE
    BEGIN
		SELECT '0'
	END

-- ------------------------------------ PROCEDIMIENTOS PARA TABLA BANCO ----------------------------------

CREATE PROCEDURE AGREGABANCO (@CVEBANCO AS VARCHAR(7), @BANCO AS VARCHAR(254), @CTABANCARIA AS INT(18), @RFC AS VARCHAR(13), @MONEDA AS VARCHAR(3))
AS
	IF EXISTS (SELECT * FROM BANCO WHERE BAN_CVE_BANCO = @CVEBANCO)
    BEGIN
		SELECT '0'
	END
    ELSE
    BEGIN
		INSERT INTO BANCO (BAN_CVE_BANCO, BAN_BANCO, BAN_CTABANCARIA, BAN_RFC, BAN_MONEDA)
        VALUES (@CVEBANCO, @BANCO, @CTABANCARIA, @RFC, @MONEDA)
        SELECT '1'
	END

CREATE PROCEDURE EDITABANCO (@CVEBANCO AS VARCHAR(7), @BANCO AS VARCHAR(254), @CTABANCARIA AS INT(18), @RFC AS VARCHAR(13), @MONEDA AS VARCHAR(3)) 
AS
	IF EXISTS (SELECT * FROM BANCO WHERE BAN_CVE_BANCO = @CVEBANCO)
    BEGIN
		UPDATE BANCO SET 
        BAN_CVE_BANCO = @CVEBANCO,
        BAN_BANCO = @BANCO,
        BAN_CTABANCARIA = @CTABANCARIA,
        BAN_RFC = @RFC,
        BAN_MONEDA = @MONEDA
		WHERE BAN_CVE_BANCO = @CVE_BANCO
        SELECT '1'
	END
    ELSE
	BEGIN
		SELECT '0'
	END

CREATE PROCEDURE ELIMINABANCO (@CVEBANCO AS NVARCHAR(7))
AS
	IF EXISTS (SELECT * FROM BANCO WHERE BAN_CVE_BANCO = @CVEBANCO)
    BEGIN
		DELETE FROM BANCO WHERE BAN_CVE_BANCO = @CVEBANCO
        SELECT '1'
	END
    ELSE
    BEGIN
		SELECT '0'
	END
    
-- ----------------------------------------- PROCEDIMIENTOS PARA TABLA MOVIMIENTOS BANCARIOS -----------------------------------------------
    
CREATE PROCEDURE AGREGAMOVIMIENTO (
	@MOV_UUID AS VARCHAR(36)PRIMARY KEY NOT NULL,
	@MOV_SERIE AS VARCHAR (25),
	@MOV_FOLIO AS VARCHAR(40),
	@MOV_FECHAPAGO AS DATETIME,
	@MOV_BANCO AS VARCHAR(3),
	@MOV_CTABANCO AS INT(18),
	@MOV_DEPOSITO AS NUMERIC(10,2),
	@MOV_ABONO AS NUMERIC(10,2),
	@MOV_RETIRO AS NUMERIC(10,2),
	@MOV_CARGO AS NUMERIC(10,2),
	@MOV_SALDO AS NUMERIC(10,2),
    @MOV_MANUAL AS BINARY,
	@BAN_CVE_BANCO AS VARCHAR(7)
    )
AS
	IF EXISTS (SELECT * FROM MOVIMIENTOBANCARIO WHERE MOV_UUID = @MOV_UUID)
    BEGIN
        SELECT '0'
	END
    ELSE
    BEGIN
		INSERT INTO MOVIMIENTOBANCARIO (MOV_UUID, MOV_SERIE, MOV_FOLIO, MOV_FECHAPAGO, MOV_BANCO, MOV_CTABANCO, MOV_DEPOSITO, MOV_ABONO, MOV_RETIRO, MOV_CARGO, MOV_SALDO, MOV_MANUAL, BAN_CVE_BANCO)
		VALUES (@MOV_UUID, @MOV_SERIE, @MOV_FOLIO, @MOV_FECHAPAGO, @MOV_BANCO, @MOV_CTABANCO, @MOV_DEPOSITO, @MOV_ABONO, @MOV_RETIRO, @MOV_CARGO, @MOV_SALDO, @MOV_MANUAL, @BAN_CVE_BANCO)
        SELECT '1'
	END
    
CREATE PROCEDURE EDITAMOVIMIENTO (MOV_UUID, MOV_SERIE, MOV_FOLIO, MOV_FECHAPAGO, MOV_BANCO, MOV_CTABANCO, MOV_DEPOSITO, MOV_ABONO, MOV_RETIRO, MOV_CARGO, MOV_SALDO, MOV_MANUAL, BAN_CVE_BANCO)
AS
	IF EXISTS (SELECT * FROM MOVIMIENTOBANCARIO WHERE MOV_UUID = @MOV_UUID)
    BEGIN
		IF (SELECT MOV_MANUAL FROM MOVIMIENTOBANCARIO WHERE MOV_UUID) = 1
        BEGIN
			UPDATE MOVIEMIENTOBANCARIO SET 
			MOV_UUID = @MOV_UUID,
			MOV_SERIE = @MOV_SERIE,
			MOV_FOLIO  = @MOV_FOLIO,
			MOV_FECHAPAGO = @MOV_FECHAPAGO,
			MOV_BANCO = @MOV_BANCO,
			MOV_CTABANCO = @MOV_CTABANCO,
			MOV_DEPOSITO = @MOV_DEPOSITO,
			MOV_ABONO = MOV_ABONO,
			MOV_RETIRO = @MOV_RETIRO,
			MOV_CARGO = @MOV_CARGO,
			MOV_SALDO = @MOV_SALDO,
			BAN_CVE_BANCO = @BAN_CVE_BANCO
			WHERE MOV_UUID = @MOV_UUID
			SELECT '1'
        END
        ELSE
        BEGIN
			SELECT '0'
		END
	END
    ELSE
    BEGIN
		SELECT '0'
	END
    
CREATE PROCEDURE ELIMINAMOVIMIENTO (MOV_UUID AS NVARCHAR (36))
AS
	IF EXISTS (SELECT * FROM MOVIMIENTOBANCARIO WHERE MOV_UUID = @MOV_UUID)
    BEGIN
		DELETE FROM MOVIMIENTOBANCARIO WHERE MOV_UUID = @MOV_UUID
        SELECT '1'
	END
    ELSE
    BEGIN
		SELECT '0'
	END
    
CREATE PROCEDURE CONSMOVIMIENTOS (@UUID AS NVARCHAR(36), @FECHA AS DATE, @RFC AS NVARCHAR(13),@DEPOSITO AS NUMERIC(10,2), @RETIRO AS NUMERIC(10,2))
AS
	IF (@UUID = "-" AND @FECHA = NULL AND RFC = "-" AND @DEPOSITO = 0.00 AND @RETIRO = 0.00)
    BEGIN
		SELECT MOV_CVE_MOVIMIENTO AS [Clave de movimiento],
		MOV_UUID AS UUID,
        MOV_SERIE AS Serie,
        MOV_FOLIO AS Folio,
        MOV_FECHAPAGO AS [Fecha de pago],
        MOV_BANCO AS Banco,
        MOV_CTABANCO AS [Cuenta bancaria],
        MOV_DEPOSITO AS Depósito,
        MOV_ABONO AS Abono,
        MOV_RETIRO AS Retiro,
        MOV_CARGO AS Cargo,
        MOV_SALDO AS Saldo
        FROM MOVIMIENTOBANCARIO
        
        WHERE MOV_UUID LIKE @UUID
        AND MOV_FECHA = @FECHA
        AND MOV_RFC LIKE @RFC
        AND MOV_DEPOSITO = @DEPOSITO
        AND MOV_RETIRO = @RETIRO