CREATE DATABASE ERPHONIX
-- CREACION DE LA BASE DE DATOS
USE ERPHONIX
-- CREACION DE TABLAS
CREATE TABLE FACTURA (
-- FAC_CVE_FACURA INT PRIMARY KEY NOT NULL IDENTITY (1,1), *
-- FAC_FACTURA BINARY, -- 0 = RECIBIDA, 1 = EMITIDA *
FAC_VERSION VARCHAR(3),
FAC_TIPOCOMPROBANTE VARCHAR(1),
FAC_FECHAEMISION DATE,
FAC_FECHATIMBRADO DATETIME,
FAC_SERIE VARCHAR(25),
FAC_FOLIO VARCHAR(40),
FAC_UUID VARCHAR(36),
FAC_RFCEMISOR VARCHAR(13),
FAC_NOMBREEMISOR VARCHAR(254),
FAC_REGIMENFISCAL VARCHAR(3),
FAC_LUGAREXPEDICION VARCHAR(5),
FAC_RFCRECEPTOR VARCHAR(13),
FAC_NOMBRERECEPTOR VARCHAR(254),
FAC_RESIDENCIAFISCAL VARCHAR(3),
FAC_NUMREGIDTRIB VARCHAR(40),
FAC_USOCFDI VARCHAR(3),
FAC_SUBTOTAL NUMERIC(10,2),
FAC_DESCUENTO NUMERIC(10,2),
FAC_TOTALIEPS NUMERIC (10,2),
FAC_IVA NUMERIC (10,2),
FAC_RETENIDOIVA NUMERIC(10,2),
FAC_RETENIDOISR NUMERIC(10,2),
-- FAC_ISH ???
FAC_TOTAL NUMERIC(10,2),
FAC_TOTALORIGINAL NUMERIC(10,2),
FAC_TOTALTRASLADADOS NUMERIC (10,2),
FAC_TOTALRETENIDOS NUMERIC(10,2),
FAC_TOTALLOCALTRA NUMERIC(10,2),
FAC_TOTALLOCALRET NUMERIC(10,2),
-- FAC_COMPLEMENTO ???
FAC_MONEDA VARCHAR(3),
-- FAC_TIPOCAMBIO NUMERIC(5,2),*
FAC_FORMAPAGO VARCHAR(2),
FAC_METODOPAGO VARCHAR(3),
-- FAC_NUMCTAPAGO INT(18),*
FAC_CONDICIONESPAGO VARCHAR(1000),
FAC_CONCEPTOS VARCHAR(1000),
)

CREATE TABLE NOMINA (
-- NOM_CVE_NOMINA INT PRIMARY KEY NOT NULL IDENTITY(1,1),*
-- NOM_VERIFOASOC ???,*
-- NOM_ESTADOSAT VARCHAR (10),*
NOM_FECHA DATE,
NOM_SERIE VARCHAR(25),
NOM_FOLIO VARCHAR(40),
NOM_UUID VARCHAR(36),
NOM_RFCRECEPTOR VARCHAR(13),
NOM_NOMBRERECEPTOR VARCHAR(254),
NOM_RFCEMISOR VARCHAR(13),
NOM_NOMBREEMISOR VARCHAR(254),
-- NOM_REGISTROPATRONAL VARCHAR(15),*
-- NOM_PATRONORIGEN ???*
-- NOM_TIPONOMINA VARCHAR(15),*
-- NOM_FECHAPAGO DATE,*
-- NOM_FECHAINICIALPAGO DATE,*
-- NOM_FECHAFINALPAGO DATE,*
-- NOM_NUMDIASPAGADOS NUMERIC(?,2),*
NOM_SUBTOTAL NUMERIC(10,2),
NOM_DESCUENTO NUMERIC(10,2),
-- NOM_ISRXML NUMERIC (?,?),*
NOM_TOTAL NUMERIC(10,2),
NOM_METODOPAGO VARCHAR(3),
NOM_REGIMENFISCAL VARCHAR(3),
-- NOM_ARCHIVO VARCHAR(?),*
NOM_CONCEPTOS VARCHAR(1000),
NOM_TIPOCOMPROBANTE VARCHAR(1),
NOM_VERSION VARCHAR(3),
NOM_MONEDA VARCHAR(3),
-- NOM_TIPOCAMBIO NUMERIC(?,2),*
-- NOM_ORIGENRECURNFC ???,*
-- NOM_MONTORECURPROPNFC ???,*
NOM_RECEPTORCURP VARCHAR(18),
-- NOM_NUMSEGSOCIAL VARCHAR(15),*
NOM_FECHAINIRELLAB DATE,
-- NOM_ANTIGUEDAD VARCHAR(5),*
-- NOM_TIPOCONTRATO VARCHAR(70),*
-- NOM_SINDICALIZADO BINARY*
-- NOM_TIPOJORNADA VARCHAR(15),*
-- NOM_TIPOREGIMEN VARCHAR(30),*
-- NOM_NUMEMPLEADO TINYINT,*
-- NOM_DEPARTAMENTO VARCHAR(25),*
-- NOM_PUESTO VARCHAR(25),*
-- NOM_RIESGOPUESTO ???*
-- NOM_PERIOINIPAGO VARCHAR(20),*
-- NOM_BANCO INT*
NOM_CTABANCARIA INT,
-- NOM_SALDOBACOAP NUMERIC(10,2),*
-- NOM_SALARIODI NUMERIC(10,2),*
NOM_CVEENTFED VARCHAR(3),
NOM_TOTALSUELDOSPER NUMERIC(10,2),
NOM_TOTALSEPINDPER NUMERIC(10,2),
NOM_TOTALJUBPENSRET NUMERIC(10,2),
NOM_TOTALEXENTOPER NUMERIC(10,2),
NOM_TOTALOTRASDED NUMERIC(10,2),
NOM_TOTALIMPRETEN NUMERIC(10,2),
)

CREATE TABLE EMPRESA (
EMP_RFC VARCHAR(13) NOT NULL PRIMARY KEY,
EMP_NOMBRE VARCHAR(254),
-- EMP_DIRECCION VARCHAR(254)*
)

CREATE TABLE BANCOS (
)

-- AVANCE HASTA 2018-08-08--