CREATE DATABASE ERPHONIX
-- CREACION DE LA BASE DE DATOS
USE ERPHONIX
-- CREACION DE TABLAS
CREATE TABLE FACTURA (
-- FAC_CVE_FACURA INT PRIMARY KEY NOT NULL IDENTITY (1,1), *
-- FAC_FACTURA BINARY, -- 0 = RECIBIDA, 1 = EMITIDA *
FAC_VERSION VARCHAR(3),
FAC_TIPOCOMPROBANTE VARCHAR(1),
FAC_FECHAEMISION DATE,
FAC_FECHATIMBRADO DATETIME,
FAC_SERIE VARCHAR(25),
FAC_FOLIO VARCHAR(40),
FAC_UUID VARCHAR(36),
FAC_RFCEMISOR VARCHAR(13),
FAC_NOMBREEMISOR VARCHAR(254),
FAC_REGIMENFISCAL VARCHAR(3),
FAC_LUGAREXPEDICION VARCHAR(5),
FAC_RFCRECEPTOR VARCHAR(13),
FAC_NOMBRERECEPTOR VARCHAR(254),
FAC_RESIDENCIAFISCAL VARCHAR(3),
FAC_NUMREGIDTRIB VARCHAR(40),
FAC_USOCFDI VARCHAR(3),
FAC_SUBTOTAL NUMERIC(10,2),
FAC_DESCUENTO NUMERIC(10,2),
FAC_TOTALIEPS NUMERIC (10,2),
FAC_IVA NUMERIC (10,2),
FAC_RETENIDOIVA NUMERIC(10,2),
FAC_RETENIDOISR NUMERIC(10,2),
-- FAC_ISH ???
FAC_TOTAL NUMERIC(10,2),
FAC_TOTALORIGINAL NUMERIC(10,2),
FAC_TOTALTRASLADADOS NUMERIC (10,2),
FAC_TOTALRETENIDOS NUMERIC(10,2),
FAC_TOTALLOCALTRA NUMERIC(10,2),
FAC_TOTALLOCALRET NUMERIC(10,2),
-- FAC_COMPLEMENTO ???
FAC_MONEDA VARCHAR(3),
-- FAC_TIPOCAMBIO NUMERIC(5,2),*
FAC_FORMAPAGO VARCHAR(2),
FAC_METODOPAGO VARCHAR(3),
-- FAC_NUMCTAPAGO INT(18),*
FAC_CONDICIONESPAGO VARCHAR(1000),
FAC_DESCRIPCION VARCHAR(1000),
)

CREATE TABLE EMPRESA (
EMP_RFC VARCHAR(13) NOT NULL PRIMARY KEY,
EMP_NOMBRE VARCHAR(254),
-- EMP_DIRECCION VARCHAR(254)*
)

CREATE TABLE BANCOS (
)

-- AVANCE HASTA 2018-08-07--